name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE'
      - 'README.md'
      - 'NEWS.md'
  pull_request:
    paths-ignore:
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE'
      - 'README.md'
      - 'NEWS.md'
  workflow_dispatch: # Allow manual triggering of the workflow from the Actions tab

# Cancel redundant CI runs: always for PRs, never for pushes to master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  prime-cache:
    name: Prime cache - ${{ matrix.version }} - ubuntu-latest - x64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['lts', '1']
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: x64
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

  test:
    needs: [prime-cache]
    name: ${{ matrix.testcase }} - ${{ matrix.version }} - ubuntu-latest - x64 - ${{ github.event_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1'
        testcase:
          - seq-geometry
          - seq-fespaces
          - seq-physics
          - seq-transient
          - seq-adaptivity
          - seq-misc
          - mpi-geometry
          - mpi-fespaces
          - mpi-physics
          - mpi-transient
          - mpi-adaptivity
          - mpi-misc
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: x64
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          TESTCASE: ${{ matrix.testcase }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.testcase }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
